spring:
  name: CoyaEngine
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    hibernate:
      ddl-auto: validate
  flyway:
    locations: "classpath:/database/migrations"
