DELETE FROM history;
ALTER SEQUENCE history_id_seq RESTART WITH 1;
DELETE FROM users;
ALTER SEQUENCE users_id_seq RESTART WITH 1;
DELETE FROM state_events;
ALTER SEQUENCE state_events_id_seq RESTART WITH 1;
DELETE FROM state_items;
ALTER SEQUENCE state_items_id_seq RESTART WITH 1;
DELETE FROM states;
ALTER SEQUENCE states_id_seq RESTART WITH 1;
DELETE FROM events;
ALTER SEQUENCE events_id_seq RESTART WITH 1;
DELETE FROM items;
ALTER SEQUENCE items_id_seq RESTART WITH 1;
-- navigation_option_source needs to be cleaned before navigation_options
DELETE FROM navigation_option_source;
ALTER SEQUENCE navigation_option_source_id_seq RESTART WITH 1;
DELETE FROM navigation_options;
ALTER SEQUENCE navigation_options_id_seq RESTART WITH 1;
DELETE FROM page_translations;
ALTER SEQUENCE page_translations_id_seq RESTART WITH 1;
DELETE FROM pages;
ALTER SEQUENCE pages_id_seq RESTART WITH 1;
