# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set execution rights
        run: chmod +x ./gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Start Docker
        run: docker-compose up -d
      - name: Build with Gradle
        uses: gradle/gradle-build-action@6095a76664413da4c8c134ee32e8a8ae900f0f1f
        with:
          arguments: build
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: home/runner/work/coya_engine/coya_engine/build/reports/tests/test/
      - name: Stop Docker
        run: docker-compose down